# -*- coding: utf-8 -*-
"""SKS_DA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diTaf0fsbZZLSuKDxQ6ANEcqprBP1f9r

# 📘 **SAIKET SYSTEMS INTERNSHIP - TASK 2✅**
---
# ✅ "PROJECT-CUSTOMER CHURN ANALYSIS AND PREDICTION"
---
**2.EXPLORATORY DATA ANALYSIS (EDA)**
---
~BY AKASH. V

---

# 🧪 **Task Description:**
# - Calculate and visualize the overall churn rate
# - Explore customer distribution by demographics
# - Analyze tenure distribution
# - Investigate churn vs contract types and payment methods

# 1️⃣ Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""# 2️⃣ Load Cleaned Dataset"""

df = pd.read_csv("cleaned_churn_data.csv")

"""# 3️⃣ Overall Churn Rate"""

churn_rate = df['Churn'].value_counts(normalize=True) * 100
print("\n📈 Churn Rate (%):")
print(churn_rate)

# Pie Chart of Churn
plt.figure(figsize=(6,6))
plt.pie(df['Churn'].value_counts(), labels=['No Churn', 'Churned'],
        autopct='%1.1f%%', colors=['#66b3ff', '#ff6666'])
plt.title('Overall Customer Churn Rate')
plt.show()

"""# 4️⃣ Customer Demographics Distribution"""

# Gender
plt.figure(figsize=(6,4))
sns.countplot(x='gender_Male', hue='Churn', data=df)
plt.title('Churn by Gender')
plt.xlabel('Gender (1 = Male)')
plt.ylabel('Count')
plt.show()

# Senior Citizen
plt.figure(figsize=(6,4))
sns.countplot(x='SeniorCitizen', hue='Churn', data=df)
plt.title('Churn by Senior Citizen Status')
plt.show()

# Partner
plt.figure(figsize=(6,4))
sns.countplot(x='Partner', hue='Churn', data=df)
plt.title('Churn by Partner Status')
plt.show()

# Dependents
plt.figure(figsize=(6,4))
sns.countplot(x='Dependents', hue='Churn', data=df)
plt.title('Churn by Dependent Status')
plt.show()

"""# 5️⃣ Tenure Distribution"""

plt.figure(figsize=(10,6))
sns.histplot(data=df, x='tenure', bins=30, kde=True, hue='Churn', palette='Set2')
plt.title('Tenure Distribution by Churn Status')
plt.xlabel('Tenure (months)')
plt.ylabel('Number of Customers')
plt.show()

"""# 6️⃣ Churn vs Contract Type"""

contract_cols = [col for col in df.columns if 'Contract_' in col]
contract_df = df[['Churn'] + contract_cols]
contract_melt = contract_df.melt('Churn', var_name='Contract Type', value_name='Active')
contract_melt = contract_melt[contract_melt['Active'] == 1]

plt.figure(figsize=(8,5))
sns.countplot(data=contract_melt, x='Contract Type', hue='Churn')
plt.title('Churn by Contract Type')
plt.xticks(rotation=45)
plt.show()

"""# 7️⃣ Churn vs Payment Method"""

payment_cols = [col for col in df.columns if 'PaymentMethod_' in col]
payment_df = df[['Churn'] + payment_cols]
payment_melt = payment_df.melt('Churn', var_name='Payment Method', value_name='Used')
payment_melt = payment_melt[payment_melt['Used'] == 1]

plt.figure(figsize=(10,5))
sns.countplot(data=payment_melt, x='Payment Method', hue='Churn')
plt.title('Churn by Payment Method')
plt.xticks(rotation=45)
plt.show()

"""# 📊**Skills Gained:**
# - Statistical analysis
# - Data visualization (Seaborn/Matplotlib)
# - Interpreting trends and patterns

### ✅ **Conclusion – Task 2: Exploratory Data Analysis (EDA)**

In this task, we explored the distribution and behavior of various customer attributes and how they relate to churn. We calculated the overall churn rate, analyzed patterns across demographics such as gender, senior citizen status, partner, and dependents, and visualized customer tenure trends.

Additionally, we examined churn relationships with contract types and payment methods. These insights provide a strong foundation for identifying potential churn risks and building targeted strategies in upcoming tasks.

**~AKASH. V - DATA ANALYSIS INTERN AT SAIKET SYSTEMS**
"""